BOARD_WIDTH = 10
BOARD_HEIGHT = 10

DIFFICULTY = 2

SPACE_SIZE = 50

FPS = 30

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

X_DISTANCE = int((WINDOW_WIDTH - BOARD_WIDTH * SPACE_SIZE) / 2)

Y_DISTANCE = int((WINDOW_HEIGHT - BOARD_HEIGHT * SPACE_SIZE) / 2)

BRIGHTBLUE = (0, 50, 255)
WHITE = (255, 255, 255)

BGCOLOR = BRIGHTBLUE
TEXTCOLOR = WHITE

RED = 'red'
BLACK = 'black'
EMPTY = None
HUMAN = 'human'
COMPUTER = 'computer'


#global FPSCLOCK, DISPLAYSURF, REDPILERECT, BLACKPILERECT, REDTOKENIMG
#global BLACKTOKENIMG, BOARDIMG, ARROWIMG, ARROWRECT, HUMANWINNERIMG
#global COMPUTERWINNERIMG, WINNERRECT, TIEWINNERIMG